### ISSUE TITLE
Frontend pipeline overview

### ISSUE THREAD

**Issue by RasmusUK** [gh05tdog/DAPM_Master_Thesis_Group_D#100]
![image](https://github.com/user-attachments/assets/237485eb-aae8-4a60-b62a-63217a21ccf0)

**Comment by ravvnen** [comment]
This issue will be split into smaller tasks  to improve traceability, and keep momentum, and this will just be a "wrapper" issue for this:
1. Get components from MUI, so we have the building blocks.
2. Step-by-step integrate the new components
