### ISSUE TITLE
Create User 

### ISSUE THREAD

**Issue by xDelux** [gh05tdog/DAPM_Master_Thesis_Group_D#145]
Story: 
As a user, I want to create a user from the frontend instead of using the keycloak back-office administration.
---------
It would be nice to just call the Keycloak API directly instead utilizing the Keycloak Backoffice.

We need a button to create user ( Hide from non admin users if possible )
Modal or page containing a form to insert user data
Feedback on user creatton or invalid input

**Comment by RasmusUK** [comment]
@xDelux Maybe we should also consider being able to add a role to the user when creating the user - like a dropdown with the 5 manager roles: Pipeline Manager, Organization Manager, Resource Manager, Repository Manager, Manager. You should be able to assign multiple roles.
