### ISSUE TITLE
Bug, changing manage page, keeps current selected object in dropdown

### ISSUE THREAD

**Issue by HLLissau** [gh05tdog/DAPM_Master_Thesis_Group_D#164]
Bug:
When an item is chosen from a dropdown (ie manage organisation) and the user changes to another mange page, the currently selected item from the dropdown persists to the new page.
organisation:

![image](https://github.com/user-attachments/assets/9ffe5741-cdb3-4d3e-8967-b87a9cead7f6)

changed to pipeline:

![image](https://github.com/user-attachments/assets/9d27d257-d30d-487d-9535-8834d45539f1)

**Comment by Martin-Surlykke** [comment]
This was fixed in the last PR
