### ISSUE TITLE
Sprint 3 cleanup and refactoring

### ISSUE THREAD

**Issue by HLLissau** [gh05tdog/DAPM_Master_Thesis_Group_D#165]
This issue is related to finalizing sprint 3.

* Remove imports which are not used 
![image](https://github.com/user-attachments/assets/49f615a6-96d1-4bdb-9256-902c1ec78d17)

* Minor layout changes, centering items ect.

* Investigate and handle console errors on front- end.
![image](https://github.com/user-attachments/assets/99cd9e35-a4db-42db-bdd8-0baa1ab64ada)

* Start execution should be changed to hit backend (done)

* We have a lot of files we dont know if we need

* After refactoring of the manager views, lots of unused files need to be removed

**Comment by gh05tdog** [comment]
Moved to sprint 4

**Comment by RasmusUK** [comment]
Too late
