### ISSUE TITLE
Pipeline e2e tests

### ISSUE THREAD

**Issue by RasmusUK** [gh05tdog/DAPM_Master_Thesis_Group_D#47]
- Test all four endpoints for pipelines.
- Create new test class `PipelineTest.cs` in `DAPM.ClientApi.Test.EndToEnd`
- Please take inspiration from `OrganizationTest.cs` and reuse the functionality. 
- Use unauthenticated client. (We will add authentication later and see the existing ones fail).
![image](https://github.com/user-attachments/assets/5f88738f-2302-497d-82ee-51103a63bf27)

**Comment by gh05tdog** [comment]
Closed cause no longer in scope
