### ISSUE TITLE
Resource e2e tests

### ISSUE THREAD

**Issue by RasmusUK** [gh05tdog/DAPM_Master_Thesis_Group_D#49]
- Test all four endpoints for pipelines.
- Create new test class `ResourceTest.cs` in `DAPM.ClientApi.Test.EndToEnd`
- Please take inspiration from `OrganizationTest.cs` and reuse the functionality. 
![image](https://github.com/user-attachments/assets/dab30e8d-ce7e-41b6-bd59-ee396605fe09)

**Comment by gh05tdog** [comment]
Closed cause no longer in scope
