### ISSUE TITLE
Repository E2E ts, Continued

### ISSUE THREAD

**Issue by HLLissau** [gh05tdog/DAPM_Master_Thesis_Group_D#63]
Original issue was split to match Sprint1. This is the remaining work, which should be completed when the API's are implemented in the frontend
Test all four endpoints for pipelines.
Create new test class RepositoryTest.cs in DAPM.ClientApi.Test.EndToEnd
Please take inspiration from OrganizationTest.cs and reuse the functionality.
Use unauthenticated client. (We will add authentication later and see the existing ones fail).
![repositoryapi](https://github.com/user-attachments/assets/22d73113-c56c-4cfb-9480-12a47de9a4a4)

**Comment by gh05tdog** [comment]
Closed cause its no longer in scope
